apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: gh-ocp-oauth-patch
  namespace: openshift-config
spec:
  serviceAccountRef:
    name: default
  patches:
    github-ocp-oauth-provider:
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: OAuth
        name: cluster
      patchTemplate: |
        spec:
          identityProviders:
          - name: backstage-demo-github 
            mappingMethod: claim
            type: GitHub
            github:
              clientID: "{{ (index . 1).data.client_id | b64dec }}" 
              clientSecret: 
                name: ocp-github-app-credentials
              organizations: 
              - che-incubator
          - name: htpasswd_provider
            mappingMethod: claim
            type: HTPasswd
            htpasswd:
              fileData:
                name: htpasswd-secret  
      patchType: application/merge-patch+json
      sourceObjectRefs:
      - apiVersion: v1
        kind: Secret
        name: ocp-github-app-credentials
        namespace: openshift-config